server:
  port: 8081
spring:
  mail:
    username: XXXX@qq.com #你的邮箱
    password: XXXX #授权码
    host: smtp.qq.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.qq.com
    port: 587

she:
  mail: XXXX@qq.com #女朋友邮箱